config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :orders
  resources :publications
  namespace :admin do
    resources :announcements
    resources :members
    resources :projects
    resources :users
    resources :notifications
    resources :services
    root to: "users#index"
  end

  resources :publications
  resources :projects do
    member do
      delete :delete_image
    end
  end
  resources :members
  get '/contact', to: 'home#contact'
  get '/soignant', to: 'home#soignant'
  get '/ingenieur', to: 'home#ingenieur'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/autres_demandes', to: 'home#autres_demandes'
  get '/infrastructure', to: 'home#infrastructure'
  get '/remerciements', to: 'home#remerciements'
  get '/workflow', to: 'home#workflow'
  get '/collaboration', to: 'home#collaboration'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-3.amazonaws.com/covid3d-production/sitemap.xml.gz")

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_one_attached :image
  enum category: [:presse, :publication]
end

app/controllers/admin/publications_controller.rb
module Admin
  class PublicationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.order("date DESC")
    @featured = Publication.where(featured: true)
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    authorize @publication
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    authorize @publication
  end

  # GET /publications/1/edit
  def edit
    authorize @publication
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    authorize @publication

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    authorize @publication
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    authorize @publication
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :date, :link, :comment, :category, :featured, :image)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :status, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.collection_select :category,
                                 Publication.categories.map { |cat| [cat.first, cat.first] },
                                 :first,
                                 :second,
                                 class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :date, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.date_select :date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :link, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :link, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :comment, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :comment, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :featured, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <%= form.check_box :featured, class: 'form-check-input', id: 'check1' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <% if publication.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', publication, method: :delete, class: "text-danger", data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if publication.persisted? %>
      <%= link_to "Cancel", publication, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", publications_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div class="col mb-4">
  <div class="card bg-light">
    <div class="card-header text-muted">
      <% if policy(publication).update? %>
        <%= link_to edit_publication_path(publication), class: 'btn btn-primary btn-sm' do %>
          <%= fa_icon('edit') %>
        <% end %>
      <% end %>
      <%= publication.category.capitalize %>
      <%= publication.date %>
    </div>
    <div class="card-body text-dark">
      <h5 class="card-title">
        <%= link_to publication.link do %>
          <%= publication.title %>
        <% end %>
      </h5>
      <p class="card-text">
        <%= publication.comment %>
      </p>
    </div>
  </div>
</div>

app/views/publications/_publication_row.html.erb
<tr>
  <td>
    <%= link_to publication.link do %>
      <%= publication.title %>
    <% end %>
  </td>
  <td>
    <%= publication.date %>
  </td>
  <td>
    <%= publication.comment %>
  </td>
  <td>
    <% if policy(publication).update? %>
      <%= link_to edit_publication_path(publication), class: 'btn btn-primary btn-sm' do %>
        <%= fa_icon('edit') %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/publications/edit.html.erb
<h1>Edit Publication</h1>

<%= render 'form', publication: @publication %>

app/views/publications/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>
      <%= fa_icon("newspaper") %>
      Presse & Publications
      <%= link_to new_publication_path, class: 'btn btn-primary' do %>
        <%= fa_icon('plus') %>
      <% end %>
    </h1>
    <p class="lead text-muted">
      Voici les articles et publications concernant notre initiative COVID3D
    </p>
  </div>
</section>

<p>
  <a class="btn btn-outline-primary" href="#presse">Presse</a>
  <a class="btn btn-outline-primary" href="#publications">Publications</a>
</p>

<div id="presse">
  <h2>Sélection presse</h2>
  <div class="row row-cols-1 row-cols-md-3">
    <% @featured.each do |publication| %>
      <% cache publication do %>
        <%= render publication %>
      <% end %>
    <% end %>
  </div>

  <h2>Presse</h2>
  <table class="table table-responsive">
    <tbody>
    <%= render partial: 'publications/publication_row', collection: @publications.presse, as: :publication, cached: true %>
    </tbody>
  </table>
</div>

<div id="publications">
  <h2>Publications</h2>
  <div class="row row-cols-1 row-cols-md-3">
    <% @publications.publication.each do |publication| %>
      <% cache publication do %>
        <%= render publication %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form', publication: @publication %>

app/views/publications/show.html.erb
<div class="page-header">
  <%= link_to publications_path, class: 'btn btn-default' do %>
    All Publications
  <% end %>
  <%= link_to edit_publication_path(@publication), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show publication</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @publication.title %></dd>

  <dt>Date:</dt>
  <dd><%= @publication.date %></dd>

  <dt>Link:</dt>
  <dd><%= @publication.link %></dd>

  <dt>Comment:</dt>
  <dd><%= @publication.comment %></dd>

  <dt>Featured:</dt>
  <dd><%= @publication.featured %></dd>
</dl>