config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :orders
  resources :publications
  namespace :admin do
    resources :announcements
    resources :members
    resources :projects
    resources :users
    resources :notifications
    resources :services
    root to: "users#index"
  end

  resources :publications
  resources :projects do
    member do
      delete :delete_image
    end
  end
  resources :members
  get '/contact', to: 'home#contact'
  get '/soignant', to: 'home#soignant'
  get '/ingenieur', to: 'home#ingenieur'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/autres_demandes', to: 'home#autres_demandes'
  get '/infrastructure', to: 'home#infrastructure'
  get '/remerciements', to: 'home#remerciements'
  get '/workflow', to: 'home#workflow'
  get '/collaboration', to: 'home#collaboration'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-3.amazonaws.com/covid3d-production/sitemap.xml.gz")

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light d-none d-sm-block">
  <div class="container">
    <ul class="list-inline mb-0 float-right">

      <li class="list-inline-item mr-3">
        <%= mail_to "philippe@cochin.fr", "Contact technique", subject: "Site 3D COVID", encode: "hex" %></li>
      <li class="list-inline-item mr-3"><%= link_to "CGU", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Politique de confidentialité", privacy_path %></li>
      <li class="list-inline-item mr-3">
        <%= render "shared/login_items" %>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_form_demande.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h3>Formulaire de demande</h3>
      <br />
      <form>
        <h5>Informations de contact</h5>
        <br />
       
        <div class="form-group row">
          <label for="email" class="col-sm-3 col-form-label">Nom</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="email" placeholder="Jean Dupont">
          </div>
        </div>
        
        <div class="form-group row">
          <label for="email" class="col-sm-3 col-form-label">Email</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="email" placeholder="jean.dupont@aphp.fr">
          </div>
        </div>

        <div class="form-group row">
          <label for="email" class="col-sm-3 col-form-label">Service & Hôpital</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="email" placeholder="Réanimation Cochin">
          </div>
        </div>

        <hr />
        <h5>Informations sur la demande</h5>
          <div class="form-group row">
            <div class="col-sm">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Merci d'expliquer ici votre besoin sanitaire urgent et fournir d'autres informations qui vous semblent importantes."></textarea>
          </div>
        </div>

        <button type="submit" class="btn btn-primary mb-3">Envoyer la demande</button>
        
      </form>
    </div>
  </div>
</div>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? %>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.dig(:google_analytics) %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', '<%= Rails.application.credentials.dig(:google_analytics) %>');
</script>
<% end %>

app/views/shared/_head.html.erb
<title>COVID3D APHP: Impression 3D pour la crise COVID</title>
<meta name="description" content="Fédération des initiatives de conception et d’impression 3D pour lutter contre le COVID-19 en Île-de-France" />
<meta name="keywords" content="COVID3D, COVID, Impression 3D, APHP" />

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_login_items.html.erb
<% if user_signed_in? %>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<% else %>
<%= link_to('Accès APHP', new_user_session_path) %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "3D COVID", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Conseil Scientifique", members_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Projets", projects_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Structure</a>
          <div class="dropdown-menu">
            <%= link_to "Ferme d'impression", infrastructure_path, class: "dropdown-item" %>
            <%= link_to "Flux de travail", workflow_path, class: "dropdown-item" %>
            <%= link_to "Collaboration", collaboration_path, class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to "Nouvelles", announcements_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Presse", publications_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%- if current_user.try(:admin) %>
            <%= link_to "Admin", admin_members_path, class: "nav-link text-danger" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_nuage_logos.html.erb
<%= image_tag("logos/logo-ministere-sante.png", height: "100px", alt: "Ministère des solidarités et de la santé") %>
<%= image_tag("logos/logo-dgos.jpg", height: "100px", alt: "Direction générale de l'offre de soins") %>
<%= image_tag("logos/logo-univ-paris.jpg", height: "100px", alt: "Université de Paris") %>
<%= image_tag("logos/logo-sauver-la-vie.jpg", height: "100px", alt: "Sauver la vie") %>
<%= image_tag("logos/logo-ageps.jpg", height: "100px", alt: "AGEPS") %>
<%= image_tag("logos/logo-AMC-banner.png", height: "100px", alt: "AMC") %>
<%= image_tag("logos/logo-ilumens.jpg", height: "100px", alt: "iLumens") %>
<%= image_tag("logos/logo-imagine.jpg", height: "100px", alt: "Imagine") %>
<%= image_tag("logos/logo-centrale.jpg", height: "100px", alt: "CentraleSupélec | Université Paris-Saclay") %>
<%= image_tag("logos/logo-URB2i.png", height: "100px", alt: "URB2i") %>
<%= image_tag("logos/logo-HEGP.jpg", height: "100px", alt: "HEGP") %>
<%= image_tag("logos/logo-ensta.jpg", height: "100px", alt: "ENSTA") %>
<%= image_tag("logos/logo-bone3d.png", height: "100px", alt: "BONE 3D") %>
<%= image_tag("logos/logo-AAA-banner.png", height: "100px", alt: "Action Aide Asie") %>
<%= image_tag("logos/logo-arts-et-metiers.png", height: "100px", alt: "Arts et Métiers") %>
<%= image_tag("logos/logo-biomechanique.jpeg", height: "100px", alt: "Institut de biomécanique humaine Georges Charpak") %>
<%= image_tag("logos/logo-ville-de-paris.png", height: "100px", alt: "Ville de Paris") %>
<%= image_tag("logos/logo-imsia.jpeg", height: "100px", alt: "IMSIA") %>
<%= image_tag("logos/logo-JOGL.jpeg", height: "100px", alt: "JOGL") %>
<%= image_tag("logos/logo-andera.png", height: "100px", alt: "Andera") %>