config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :orders
  resources :publications
  namespace :admin do
    resources :announcements
    resources :members
    resources :projects
    resources :users
    resources :notifications
    resources :services
    root to: "users#index"
  end

  resources :publications
  resources :projects do
    member do
      delete :delete_image
    end
  end
  resources :members
  get '/contact', to: 'home#contact'
  get '/soignant', to: 'home#soignant'
  get '/ingenieur', to: 'home#ingenieur'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/autres_demandes', to: 'home#autres_demandes'
  get '/infrastructure', to: 'home#infrastructure'
  get '/remerciements', to: 'home#remerciements'
  get '/workflow', to: 'home#workflow'
  get '/collaboration', to: 'home#collaboration'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-3.amazonaws.com/covid3d-production/sitemap.xml.gz")

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: %i[slugged history]
  enum validation: %i[prototype clinical_validation validated]
  enum category: %i[comfort medical_device workgroup repair]
  enum material: %i[ABS PLA ASA PETG Any]

  has_and_belongs_to_many :members
  has_one_attached :thumbnail
  has_many_attached :images
  has_many_attached :stls

  before_save :compile_markdown

  def compile_markdown
    return unless self.description.present?
    self.description_html =
        Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true).
            render(self.description)
  end

  def category_text
    if self.comfort?
      return "Matériel de protection et de comfort"
    elsif self.medical_device?
      return "Dispositif médical"
    elsif self.workgroup?
      return "Recherche & Developpement"
    end
  end

  def validation_text
    if self.prototype?
      return "En cours de prototypage"
    elsif self.clinical_validation?
      return "Validation clinique effectuée"
    elsif self.validated?
      return "Validation finale effectuée"
    end
  end

  def image_url
    'https://covid3d.org' + Rails.application.routes.url_helpers.rails_blob_path(self.images.first, only_path: true) if self.images.attached?
  end

  def stls_url
    urls = []
    self.stls.each do |stl|
      urls << 'https://covid3d.org' + Rails.application.routes.url_helpers.rails_blob_path(stl, only_path: true)
    end
    return urls
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = policy_scope(Project)
                    .with_attached_images
                    .with_attached_stls
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    authorize @project

    if request.path != project_path(@project)
      redirect_to @project, status: :moved_permanently
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project

    params[:project][:member_ids].each do |member_id|
      unless member_id.empty?
        member = Member.find(member_id)
        @project.members << member
      end
    end

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge # or use purge_later
    redirect_back(fallback_location: projects_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = policy_scope(Project).friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(
        :name,
        :plural_name,
        :description,
        :description_html,
        :short_description,
        :status,
        :validation,
        :category,
        :published,
        :assembly,
        :printer_settings,
        :comments,
        :fdm,
        :advanced,
        :cnc,
        :lasercutter,
        :electronics,
        :silicone,
        :author,
        :author_url,
        :website,
        :license,
        :material,
        :layer_size,
        :fill_density,
        :support,
        :raft,
        :estimated_time,
        images: [],
        stls: [],
        member_ids: []
    )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_status_in_words(project)
    {
      "1" => "en cours de prototypage",
      "2" => "en cours de validation",
      "3" => "en cours de diffusion"
    }[project.status]
  end
end

app/views/projects/_card.html.erb
<div class="card shadow-sm">

  <% if project.images.attached? %>
    <%= image_tag(project.images.first.variant(resize_to_fit: [400, 300]).processed, class: "card-img-top", alt: project.short_description) %>
  <% else %>
    <%= image_tag("cards/carte-autres-43.png", class: "card-img-top", alt: project.short_description) %>
  <% end %>

  <div class="card-header">
    <%= link_to project, class: "stretched-link" do %>
      <%= project.name %>
    <% end %>
    <p class="text-muted small">
      <%= project.validation_text %>
    </p>
  </div>
</div>

app/views/projects/_card_description.html.erb
<div class="card border-light">
  <h4 class="card-header text-center">Description</h4>
  <div class="card-body">
    <%== project.description_html %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <b>Validation: </b>
        <%= project.validation_text %>
      </li>
      <li class="list-group-item">
        <b>Catégorie: </b>
        <%= project.category_text %>
      </li>
      <li class="list-group-item">
        <b>License: </b>
        <%= project.license %>
      </li>
    </ul>
    <p class="card-text">
      <small class="text-muted">
        Mise à jour le <%= project.updated_at %>
      </small>
    </p>
  </div>
</div>

app/views/projects/_card_impression.html.erb
<div class="card">
  <h4 class="card-header text-center">Impression 3D</h4>
  <div class="card-body">
    <h5 class="card-title">STLs et fichiers</h5>
    <% if @project.stls.attached? %>
      <ul class="list-unstyled">
        <% @project.stls.each do |stl| %>
          <li>
            <%= link_to rails_blob_path(stl, disposition: 'attachment'), class: "btn btn-outline-primary" do %>
              <%= stl.filename %>
              <%= fa_icon 'download' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      Aucun STL n'a encore été publié.
    <% end %>
    <br/>
    <h5 class="card-title">Paramètres d'impression</h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <b>Matériel recommandé: </b>
        <%= project.material %>
      </li>
      <li class="list-group-item">
        <b>Hauteur de strate: </b>
        <%= project.layer_size %>mm
      </li>
      <li class="list-group-item">
        <b>Densité de remplissage: </b>
        <%= project.fill_density %>%
      </li>
      <li class="list-group-item">
        <b>Supports structurels: </b>
        <%= project.support ? 'Oui' : 'Non' %>
      </li>
      <li class="list-group-item">
        <b>Base: </b>
        <%= project.raft ? 'Oui' : 'Non' %>
      </li>
      <li class="list-group-item">
        <b>Temps estimé par pièce: </b>
        <%= project.estimated_time %>mn
      </li>
    </ul>
    <br/>
    <h5 class="card-title">Technologies utilisées</h5>
    <ul>
      <% if @project.fdm %>
        <li>FDM</li>
      <% end %>
      <% if @project.advanced %>
        <li>Advanced printer</li>
      <% end %>
      <% if @project.cnc %>
        <li>CNC</li>
      <% end %>
      <% if @project.lasercutter %>
        <li>Lasercutter</li>
      <% end %>
      <% if @project.electronics %>
        <li>Electronics</li>
      <% end %>
      <% if @project.silicone %>
        <li>Silicone</li>
      <% end %>
    </ul>
    <% if @project.printer_settings.present? %>
      <h5 class="card-title">Informations complémentaires:</h5>
      <%= @project.printer_settings %>
    <% end %>
    <% if @project.assembly.present? %>
      <h5 class="card-title">Assemblage</h5>
      <%= @project.assembly %>
    <% end %>

  </div>
</div>

app/views/projects/_card_team.html.erb
<div class="card border-light">
  <h4 class="card-header text-center">Equipe</h4>
  <div class="card-body">
    <h5 class="card-title">Groupe de travail: </h5>
    <ul class="list-group list-group-flush">
      <% project.members.each do |member| %>
        <li class="list-group-item">
          <%= member.name %>
        </li>
      <% end %>
    </ul>
    <br/>
    <h5 class="card-title">Designer</h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <b>Auteur: </b>
        <%= project.author %>
      </li>
      <% if project.author_url %>
        <li class="list-group-item">
          <b>Site Web de l'auteur: </b>
          <%= link_to project.author_url, project.author_url %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/_carrousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% project.images.each_with_index do |image, index| %>
      <% if index == 0 %>
        <div class="carousel-item active">
          <%= image_tag(image.variant(resize_to_limit: [800, 600]).processed, class: "d-block w-100") %>
        </div>
      <% else %>
        <div class="carousel-item">
          <%= image_tag(image.variant(resize_to_limit: [800, 600]).processed, class: "d-block w-100") %>
        </div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Description</h2>
  <div class="form-group row">
    <%= form.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :short_description, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :short_description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :category, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.collection_select :category,
                                 Project.categories.map { |cat| [cat.first, cat.first] },
                                 :first,
                                 :second,
                                 class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :validation, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.collection_select :validation,
                                 Project.validations.map { |cat| [cat.first, cat.first] },
                                 :first,
                                 :second,
                                 class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :license, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :license, class: 'form-control', value: "CERN-OHL-P" %>
    </div>
  </div>

  <hr/>
  <h2>Equipe</h2>
  <div class="form-group row">
    <%= form.label :members, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= collection_select(:project, :member_ids, Member.order(:last_name), :id, :name, {}, {:multiple => true}) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :author, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :author, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :author_url, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :author_url, class: 'form-control' %>
    </div>
  </div>

  <hr/>
  <h2>Impression 3D</h2>
  <div class="form-group row">
    <%= form.label "STLs", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.file_field :stls, multiple: true, class: 'form-control' %>
      <ul class="list-unstyled">
        <% @project.stls.each do |stl| %>
          <li>
            <%= link_to stl.filename, rails_blob_path(stl, disposition: 'attachment'), class: "btn btn-outline-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :material, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.collection_select :material,
                                 Project.materials.map { |cat| [cat.first, cat.first] },
                                 :first,
                                 :second,
                                 class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :layer_size, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= form.text_field :layer_size, class: 'form-control' %>
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2">mm</span>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :fill_density, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= form.text_field :fill_density, class: 'form-control' %>
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2">%</span>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Supports", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <%= form.check_box :support, class: 'form-check-input', id: 'check1' %>
        <label class="form-check-label" for="check1">Supports</label>
      </div>
      <div class="form-check form-check-inline">
        <%= form.check_box :raft, class: 'form-check-input', id: 'check2' %>
        <label class="form-check-label" for="check2">Base</label>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :estimated_time, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= form.text_field :estimated_time, class: 'form-control' %>
        <div class="input-group-append">
          <span class="input-group-text" id="basic-addon2">mn</span>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Technology", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <%= form.check_box :fdm, class: 'form-check-input', id: 'check1' %>
        <label class="form-check-label" for="check1">FDM</label>
      </div>
      <div class="form-check form-check-inline">
        <%= form.check_box :advanced, class: 'form-check-input', id: 'check2' %>
        <label class="form-check-label" for="check2">Advanced Printer</label>
      </div>
      <div class="form-check form-check-inline">
        <%= form.check_box :cnc, class: 'form-check-input', id: 'check3' %>
        <label class="form-check-label" for="check3">CNC</label>
      </div>
      <div class="form-check form-check-inline">
        <%= form.check_box :lasercutter, class: 'form-check-input', id: 'check4' %>
        <label class="form-check-label" for="check4">Laser cutter</label>
      </div>
      <div class="form-check form-check-inline">
        <%= form.check_box :electronics, class: 'form-check-input', id: 'check5' %>
        <label class="form-check-label" for="check5">Electronics</label>
      </div>
      <div class="form-check form-check-inline">
        <%= form.check_box :silicone, class: 'form-check-input', id: 'check6' %>
        <label class="form-check-label" for="check6">Silicone</label>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Infos supp.", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :printer_settings, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :assembly, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :assembly, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :comments, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :comments, class: 'form-control' %>
    </div>
  </div>

  <h2>Images</h2>
  <div class="form-group row">
    <%= form.label "Images", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.file_field :images, multiple: true, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <% @project.images.each_with_index do |image, index| %>
      <div>
        <%= image_tag(image.variant(resize_to_limit: [400, 300]).processed, class: "img-thumbnail") %>
        <%= link_to 'Remove', delete_image_project_path(id: project.id, image_id: image.id), method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <% if project.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', project, method: :delete, class: "text-danger", data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if project.persisted? %>
      <%= link_to "Cancel", project, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", projects_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<hr>
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>
      <%= fa_icon("tasks") %>
      Catalogue de projets
      <% if policy(Project.new).create? %>
      <%= link_to new_project_path, class: 'btn btn-primary' do %>
      <%= fa_icon("plus") %>
      <% end %>
      <% end %>
    </h1>
    <p class="lead text-muted">
      Nous travaillons en accord avec les dernières recommandations de l' ANSM concernant l'impression 3D en période de
      crise COVID3D :
      <%= link_to "Lire le PDF", "/documents/fiche_encadrement.pdf" %>
    </p>
  </div>
</section>

<h2>
  <%= fa_icon("user-nurse") %>
  Matériel de protection et de confort
</h2>
<br>
<div class="card-columns">
  <%= render partial: '/projects/card', collection: @projects.comfort, as: :project, cached: true %>
</div>

<hr>
<h2>
  <%= fa_icon("briefcase-medical") %>
  Equipement médical
</h2>
<br>
<div class="card-columns">
  <%= render partial: '/projects/card', collection: @projects.medical_device, as: :project, cached: true %>
</div>

<hr>
<h2>
  <%= fa_icon("flask") %>
  Recherche & développement
</h2>
<br>
<div class="card-columns">
  <%= render partial: '/projects/card', collection: @projects.workgroup, as: :project, cached: true %>
</div>

<% if @projects.repair.length > 0 %>
<hr>
<h2>
  <%= fa_icon("wrench") %>
  Maintenance
</h2>
<br>
<div class="card-columns">
  <%= render partial: '/projects/card', collection: @projects.repair, as: :project, cached: true %>
</div>
<% end %>

app/views/projects/new.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>
      Nouveau projet
    </h1>
    <p class="lead text-muted">
    </p>
  </div>
</section>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1><%= @project.name %>
      <% if policy(@project).update? %>
        <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
          <%= fa_icon('edit') %>
        <% end %>
      <% end %>
    </h1>
    <p class="lead text-muted">
      <i>
        <%= @project.category_text %> -
        <%= @project.validation_text %>
      </i>
      <br/>
      <%= @project.short_description %>
    </p>
  </div>
</section>

<%# <div class="row">
  <div class="col-sm">
    <ul class="nav nav-pills nav-justified">
      <li class="nav-item">
        <a class="nav-link active" href="#">Description</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Equipe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Impression 3D</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Notice d'assemblage</a>
      </li>
    </ul>
  </div>
</div>
<br /> %>

<div class="row">
  <div class="col-sm-6">
    <%= render partial: "carrousel", locals: {project: @project} %>
  </div>
  <div class="col-sm-6">
    <%= render partial: "card_description", locals: {project: @project} %>
  </div>
</div>

<br/>
<div class="row">
  <div class="col">
    <%= render partial: "card_impression", locals: {project: @project} %>
  </div>
  <div class="col">
    <%= render partial: "card_team", locals: {project: @project} %>
  </div>
</div>

<% if @project.comments? %>
  <div class="row">
    <div class="col">
      <div class="card">
        <h3>Commentaires</h3>
        <%= @project.comments %>
      </div>
    </div>
  </div>
<% end %>