config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :orders
  resources :publications
  namespace :admin do
    resources :announcements
    resources :members
    resources :projects
    resources :users
    resources :notifications
    resources :services
    root to: "users#index"
  end

  resources :publications
  resources :projects do
    member do
      delete :delete_image
    end
  end
  resources :members
  get '/contact', to: 'home#contact'
  get '/soignant', to: 'home#soignant'
  get '/ingenieur', to: 'home#ingenieur'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/autres_demandes', to: 'home#autres_demandes'
  get '/infrastructure', to: 'home#infrastructure'
  get '/remerciements', to: 'home#remerciements'
  get '/workflow', to: 'home#workflow'
  get '/collaboration', to: 'home#collaboration'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  get '/sitemap.xml.gz', to: redirect("https://s3-eu-west-3.amazonaws.com/covid3d-production/sitemap.xml.gz")

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  has_and_belongs_to_many :projects

  def name
    return first_name + " " + last_name
  end
end

app/controllers/admin/members_controller.rb
module Admin
  class MembersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /members
  # GET /members.json
  def index
    @members = Member.order(:last_name)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    authorize @member
  end

  # GET /members/new
  def new
    @member = Member.new
    authorize @member
  end

  # GET /members/1/edit
  def edit
    authorize @member
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    authorize @member

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    authorize @member
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    authorize @member
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = policy_scope(Member).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :job, :email, :comment)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
<% if member.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

  <ul>
    <% member.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :job %>
  <%= form.text_field :job, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :comment %>
  <%= form.text_field :comment, class: 'form-control' %>
</div>

<div class="form-group">
  <% if member.persisted? %>
  <div class="float-right">
    <%= link_to 'Destroy', member, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
  </div>
  <% end %>

  <%= form.submit class: 'btn btn-primary' %>

  <% if member.persisted? %>
  <%= link_to "Cancel", member, class: "btn btn-link" %>
  <% else %>
  <%= link_to "Cancel", members_path, class: "btn btn-link" %>
  <% end %>
</div>
<% end %>

app/views/members/_member.html.erb
# encoding: utf-8
<li>
  <%= member.name %> -
  <%= member.job %> -
  <%= mail_to member.name, member.email %>
</li>

app/views/members/_member_row.html.erb
<tr>
  <td><b><%= member.name %></b></td>
  <td><%= member.job %></td>
  <td><%= mail_to member.email, member.email, encode: "hex" %></td>
  <td><%= member.comment %></td>

  <% if policy(member).update? %>
    <td>
      <%= link_to edit_member_path(member), class: 'btn btn-primary btn-sm' do %>
        <%= fa_icon('edit') %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/members/edit.html.erb
<h1>Edit Member</h1>

<%= render 'form', member: @member %>

app/views/members/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>
      <%= fa_icon("user-shield") %>
      Conseil scientifique
      <% if policy(Member.new).create? %>
      <%= link_to new_member_path, class: 'btn btn-primary' do %>
      <%= fa_icon("user-plus") %>
      <% end %>
      <% end %>
    </h1>
    <p class="lead text-muted">
      Le Conseil Scientifique évalue les dispositifs proposés par les groupes de travail, teste les prototypes et
      participe à leur validation, avant de coordonner leur mise en fabrication par notre plateforme et nos relais
      industriels.
    </p>
  </div>
</section>

<div class="table-responsive">
  <table class="table table-hover">
    <tbody>
      <%= render partial: 'members/member_row', collection: @members, as: :member, cached: true %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form', member: @member %>

app/views/members/show.html.erb
<div class="page-header">
  <%= link_to members_path, class: 'btn btn-default' do %>
  All Members
  <% end %>
  <%= link_to edit_member_path(@member), class: 'btn btn-primary' do %>
  Edit
  <% end %>
  <h1>Show member</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @member.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @member.last_name %></dd>

  <dt>Job:</dt>
  <dd><%= @member.job %></dd>

  <dt>Email:</dt>
  <dd><%= @member.email %></dd>

  <dt>Email:</dt>
  <dd><%= @member.comment %></dd>

</dl>